"""Domain contract for parsed course decomposition plan."""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field, model_validator


def _empty_deadlines() -> list[CoursePlanDeadline]:
    return []


class SubmissionCriteria(BaseModel):
    """Optional acceptance criteria for module submissions."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    checklist: list[str] = Field(default_factory=list)
    passing_score: int | None = Field(default=None, ge=0, le=100)


class CoursePlanCourse(BaseModel):
    """Course-level metadata extracted from imported text."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    title: str = Field(min_length=1, max_length=255)
    description: str = Field(min_length=1, max_length=4000)
    start_date: date | None = None


class CoursePlanModule(BaseModel):
    """Module item in course plan."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    order: int = Field(ge=1)
    title: str = Field(min_length=1, max_length=255)
    goals: list[str] = Field(default_factory=list)
    topics: list[str] = Field(default_factory=list)
    estimated_hours: int = Field(ge=1, le=200)
    submission_criteria: SubmissionCriteria | None = None


class CoursePlanDeadline(BaseModel):
    """Deadline item linked to module order."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    order: int = Field(ge=1)
    module_ref: int = Field(ge=1)
    due_at: datetime | None = None
    kind: str = Field(min_length=1, max_length=64)
    notes: str | None = Field(default=None, max_length=1000)


class CoursePlanV1(BaseModel):
    """Validated course plan generated by LLM and edited in UI."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    course: CoursePlanCourse
    modules: list[CoursePlanModule] = Field(min_length=1)
    deadlines: list[CoursePlanDeadline] = Field(default_factory=_empty_deadlines)
    schema_version: str = Field(default="v1")

    @model_validator(mode="after")
    def validate_cross_references(self) -> CoursePlanV1:
        module_orders = [module.order for module in self.modules]
        if len(set(module_orders)) != len(module_orders):
            raise ValueError("Module order values must be unique.")

        deadline_orders = [deadline.order for deadline in self.deadlines]
        if len(set(deadline_orders)) != len(deadline_orders):
            raise ValueError("Deadline order values must be unique.")

        known_module_orders = set(module_orders)
        for deadline in self.deadlines:
            if deadline.module_ref not in known_module_orders:
                raise ValueError(
                    "Deadline order="
                    f"{deadline.order} references unknown module_ref={deadline.module_ref}."
                )

        return self
